name: AKS Production Cluster Deployment
run-name: Deploy to ${{ inputs.deploy_target }} by @{{ github.actor }}

on:
  push:
    branches:
      - master
    paths:
      - 'azure/azuredeploy.json'
      - 'azure/azuredeploy.parameters.json'

jobs:
  deploy_aks_production:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Azure Resource Manager (ARM) Template
      uses: Azure/arm-deploy@v1.0.9
      with:
        # Provide the scope of the deployment. Valid values are: 'resourcegroup', 'managementgroup', 'subscription'
        scope: resourcegroup
        # Override the Subscription Id set by Azure Login.
        subscriptionId: ${{ secrets.AzureSubscriptionId }}
        # Provide the target region, only required for management Group or Subscription deployments.
        region: 'brazilsouth'
        # Provide the name of a resource group, only required for resource Group deployments.
        resourceGroupName: $prodResourceGroupName
        # Specify the path or URL to the Azure Resource Manager template.
        template: 'azure/azuredeploy.json'
        # Incremental (only add resources to resource group) or Complete (remove extra resources from resource group) or Validate (only validates the template).
        parameters: 'azure/azuredeploy.parameters.json'